### ISSUE TITLE
项目怎么才能运行起来 

### ISSUE THREAD

**Issue by yxwandroid** [yangkun19921001/NDK_AV_SAMPLE#1]
![image](https://user-images.githubusercontent.com/9635493/84720677-49c5e680-afb1-11ea-9e6b-27cdeb1e9165.png)

**Comment by fengbuck** [comment]
我也遇到了，请问您怎么解决的

**Comment by fengbuck** [comment]
> 我也遇到了，请问您怎么解决的

ndk路径没有配置好
